### ISSUE TITLE
Pool::waitAll doesn't wait the end of all works

### ISSUE THREAD

**Issue by zup1** [tghosgor/threadpool11#11]
I have created a test case that pull some works in the pool and then wait the end of all, but sometimes the work queue is not empty. The test case is:
# include "threadpool11/threadpool11.hpp"
# include <iostream>
# include <chrono>
# include <cstdlib>
# include <unistd.h>

int main(int argc, char\* argv[]) {
  try {
    int threads = 8;
    int recursion = 1000;
    int initial_jobs = 1000;
    auto t0 = std::chrono::high_resolution_clock::now();
    threadpool11::Pool pool(threads);

```
for (int i = 0; i < initial_jobs; i++) {
    for (int depth = 0; depth < recursion; depth++)
        pool.postWork<int>([]() { usleep(10); return 0; });
    pool.waitAll();
    std::cout << "work queue size=" << pool.getWorkQueueSize() << std::endl;
}
pool.joinAll();
std::cout << "finish" << std::endl;
auto t1 = std::chrono::high_resolution_clock::now();
std::cout << "threads: " << threads << " depth: " << recursion << std::endl;
std::cout << "ns/job: "
          << std::chrono::duration_cast<std::chrono::nanoseconds>(t1 - t0).count() /
                 ((recursion + 1) * initial_jobs) << std::endl;
usleep(1000 * 1000);
```

  } catch (...) {
    std::cout << "exception" << std::endl;
  }
  return 0;
}

So I have changed the waitAll as follow:

void Pool::waitAll() {
  std::unique_lockstd::mutex lock(notify_all_finished_signal_mtx);
  if (m_activeWorkerCount > 0 || getWorkQueueSize() > 0) {
    m_notifyAllFinishedSignal.wait(lock, [this]() { return m_areAllReallyFinished && getWorkQueueSize() == 0; });
    m_areAllReallyFinished = false;
  }
}

**Comment by tghosgor** [comment]
This should not be happening. Workers make sure there are no items in the queue before signalling completion. There is a chance that works are actually finished but work queue counter is not updated but that should not happen either. I will check this when I have time. Thanks.

**Comment by tghosgor** [comment]
Yes you are right. There is a chance that you get to call `waitAll` before workers pop the posted work from queue and increase the `m_activeWorkerCount`. Your solution will work fine. I will be adding that to the repo.

Thanks for reporting the problem. I hope the library is useful to you.

**Comment by tghosgor** [comment]
Yes you are right. There is a chance that you get to call waitAll before workers pop the posted work from queue and increase the m_activeWorkerCount. Your solution will work fine. I will be adding that to the repo.

Thanks for reporting the problem. I hope the library is useful to you.

**Comment by tghosgor** [comment]
Yes you are right. There is a chance that you get to call waitAll before workers pop the posted work from queue and increase the m_activeWorkerCount. Note that this solution makes this problem *really unlikely to happen, it does not solve it*.

I will try to think of a way to solve this without using mutexes. I will probably have to use *one* atomic and bit shifting instead of having both `m_workQueueSize` and `m_activeWorkerCount`.

**Comment by tghosgor** [comment]
Yes you are right! There is a chance that you get to call `waitAll` before workers pop the posted work from queue and increase the `m_activeWorkerCount`. Note that this solution makes this problem **really unlikely to happen, it does not solve it**. Consider this:

You post a work and call `waitAll`

in `waitAll`
`m_activeWorkerCount > 0 && m_workQueueSize > 0`

Main thread checks `m_activeWorkerCount` and it is `0` because work is still in the queue.

Meanwhile in `Worker::execute()`

``` cpp
--pool.m_workQueueSize; // <-- this gets executed
++pool.m_activeWorkerCount;
```

Now main threads checks `m_workQueueSize` and it is also `0`. Now you are processing the work yet `waitAll()` returns.

I had removed the `waitAll` and some other functions and then it was added back by a pull request and I did not really check it as I don't use it. Sorry about this.

I will try to think of a way to solve this without using any more mutexes. I will probably have to use _one_ atomic and bit shifting instead of having both `m_workQueueSize` and `m_activeWorkerCount`. Or simply another separate bit to indicate we actually have finished that gets set in each postWork and reset when done.

**Comment by zup1** [comment]
I have cheched the new version, I have found an error in the Worker::execute. The value of active_worker_count_ sometimes is not correct, it's not decreased. So the condition variable notify_all_finished_signal_ doesn't notify the end of the all the workers. I have changed the condition to

if (--pool.active_worker_count_ == 0 && pool.work_queue_size_ == 0) {

**Comment by tghosgor** [comment]
Ah yeah thanks for that. Committed it. bbcfd7a20768f556c5ac4ccfb3244457660beea5
