### ISSUE TITLE
joinAll() should end only if getWorkerCount() is really zero

### ISSUE THREAD

**Issue by samuelba** [tghosgor/threadpool11#12]
it can happen, that if `joinAll()` is called twice in a short amount of time, that the code stuck inside the while loop of `decWorkerCountBy(std::numeric_limits<size_t>::max(), Method::SYNC);`. That's because not all threads are actually joined when the second `joinAll()` is called.

I solved the problem by adding `while(getWorkerCount() > 0) { }` at the end of `joinAll()`, however that's probably not the best solution.

```
void Pool::joinAll() {
    decWorkerCountBy(std::numeric_limits<size_t>::max(), Method::SYNC);
    while (getWorkerCount() > 0) { }
}
```

**Comment by tghosgor** [comment]
You are right, I should have written that in comments.

The internal work functions have a return value and that value is used deciding thread termination. But when the functions execute, the thread calling joinAll unblocks. Yet, worker count is not updated yet at that moment.

It is possible to use a worker struct instead of internal worker functions and a flag member variable instead of using a return value. Then we can decrease the worker count before unblocking the thread calling joinAll.

The related code is `work_type = (*work)();` and `if (work_type == Work::Type::TERMINAL) {` block in worker.cpp.

I will look into it if I have free time. Your solution will not cause any problems unless there are a lot of enqueued works because termination request is just another work pushed to the back of the work queue. Then your main thread will waste a little CPU time.

**Comment by tghosgor** [comment]
#17 should also fix this.
