### ISSUE TITLE
Why is this library announced "lock-free" if std::mutex and std::condition_variable is heavily used?

### ISSUE THREAD

**Issue by jasonszang** [tghosgor/threadpool11#14]
Just out of curiosity. Does that mean that some performance critical part of the thread pool is lock-free? But if I understood it right both pushing tasks and executing tasks require locking std::mutex with std::unique_lock.

**Comment by tghosgor** [comment]
Mutes is only used for signaling. If there are multiple works enqueued, the consumption of them from multiple threads does not have any blocking behavior.

Maybe additional methods can be added to bypass that signaling and directly enqueue the work. But how will the threads know there is work on queues without busy waiting? You could use an eventfd instead of conditional variables/mutex but I think it has more overhead due to kernel-mode write/read on fd etc.

Note that this project is a part of something I did as an internship assignment. Using std::future is usually slow due to its shared context setup (slow as in similar to std::shared_ptr being slow I think). It can be considered very incomplete and behavior of methods are not well-defined.

P.S. Boost.Lockfree containers are also advertised as lock-free but if you directly use it (in its non-fixed-sized mode) it will also block while doing allocation as containers grow.
